version: "3.9"

services:
  sut:
    build:
      context: ./app
    image: etl-app:test
    command: ["pytest", "-q", "--maxfail=1", "--disable-warnings", "tests/"]
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  backend:
    driver: bridge
